# Ambil dari image yang sudah ada
FROM node:latest
  # FROM mysql:latest
# copy file lokal ke image
COPY . .
# Execute program when program running
RUN npm install
# cara menjalankan filenya
CMD [ "npm","start" ]